In [1]:
%load_ext autoreload

In [2]:
%autoreload 2

In [3]:
import numpy as np

In [4]:
from catanai import Board

board = Board(random_seed=1)

board

In [5]:
board.tiles_tensor, board.harbor_tensor, board.numbers

(array([[1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0, 0]]),
 array([[0, 0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0]]),
 array([10,  5,  4, 11,  6,  2,  5, 11,  3,  8, 12,  6,  0,  4,  3, 10,  9,
         8,  9]))

In [6]:
board.dots

array([3, 4, 3, 2, 5, 1, 4, 2, 2, 5, 1, 5, 0, 3, 2, 3, 4, 5, 4])